# Generated by Django 4.0.5 on 2022-06-05 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_dob_customuser_gender_customuser_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='gender',
            field=models.CharField(blank=True, max_length=1),
        ),
    ]
