# Generated by Django 4.0.5 on 2022-06-05 12:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_customuser_dob'),
    ]

    operations = [
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('question_id', models.AutoField(primary_key=True, serialize=False)),
                ('question', models.CharField(max_length=100)),
                ('question_desc', models.TextField()),
                ('code_fld', models.TextField(default='')),
                ('created_by', models.CharField(max_length=100)),
                ('created_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('answersCount', models.IntegerField(default=0)),
            ],
        ),
    ]
