# Generated by Django 4.0.5 on 2022-06-06 18:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_customuser_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answers',
            fields=[
                ('answer_id', models.AutoField(primary_key=True, serialize=False)),
                ('answer', models.CharField(max_length=100)),
                ('answer_desc', models.TextField(default='')),
                ('code_fld', models.TextField(default='')),
                ('answered_by', models.CharField(max_length=100)),
                ('question_id', models.CharField(max_length=100)),
                ('created_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('ans_count', models.IntegerField(default=0)),
            ],
        ),
    ]
