# Generated by Django 4.0.5 on 2022-06-15 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_customuser_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='pic',
            field=models.FileField(null=True, upload_to='media/'),
        ),
    ]
