# Generated by Django 4.0.5 on 2022-06-25 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_customuser_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='pic',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
